batch_size: 512  # at least 512
epochs: 100
start_epoch: 0  # start from 0 to epochs-1
log_dir: None
eval_every_n_epochs: 1
# fine_tune_from: 'Mar30_13-47-27_2fa6544f6257'
fine_tune_from: ''
log_every_n_steps: 25
weight_decay: 10e-6
fp16_precision: False
n_gpu: 1
gpu_ids: (2,)

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 0
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True
